apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dex-vs
  namespace: dex
spec:
  hosts:
  - auth.goboolean.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: dex.dex.svc.cluster.local
        port:
          number: 5556