apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-repo-server-rolebinding
  namespace: gitops
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: gitops
roleRef:
  kind: Role
  name: argocd-repo-server-role
  apiGroup: rbac.authorization.k8s.io
