apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: darkblue31415@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stg
    solvers:
    - dns01:
        cloudflare:
          email: darkblue31415@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token