expose:
  type: ingress
  tls:
    enabled: true
    certSource: none
  ingress:
    hosts:
      core: registry.goboolean.io
    annotations:
      kubernetes.io/ingress.class: istio
externalURL: https://registry.goboolean.io

