telegraf-ds:
  replicaCount: 1

  config:
    outputs:
      - influxdb_v2:
          urls:
            - "http://influxdata-influxdb2.influxdata.svc.cluster.local:8086"
          token: "CdR0VFBDO30TVSvG8wqWUO8IEqKFext5gegv7wJqJrU19-0WaY1nUqLgbjP3X3H53H7VRZkxJw13-Z6hj_eCDg=="
          organization: "goboolean"
          bucket: "k8s"