apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-system-streams
spec:
  template:
    spec:
      containers:
      - name: fetch-system-streams
        image: "34.84.212.14:80/fetch-system-streams:79058dc34077ea5a30d04d237f315064af54773b"
        imagePullPolicy: Always
        imagePullSecrets:
        - name: harbor-registry
