apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-system-streams
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: fetch-system-streams
          image: "34.84.212.14:80/fetch-system/fetch-system-streams:79058dc34077ea5a30d04d237f315064af54773b"
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_HOST
              value: "fetch-system-kafka:9092"
            - name: ETCD_HOST
              value: "fetch-system-etcd:2379"
            - name: OTEL_ENDPOINT
              value: "fetch-system-opentelemetry-collector:4317"
