dbiniter:
  image:
    repository: registry.mulmuri.dev/fetch-system-db-initer
    tag: latest
    imagePullPolicy: Always
  env:
    postgresqlHost: fetch-system-postgresql
    postgresqlPort: 5432
    postgresqlUser: goboolean
    postgresqlPassword: ""
    postgresqlDatabase: goboolean
    polygonSecretKey: ""

workercommon:
  env:
    etcdHost: fetch-system-etcd:2379
    kafkaBootstrapHost: fetch-system-kafka:9092
    otelEndpoint: fetch-system-opentelemetry-collector:4317

worker:
  polygon-stock:
    name: polygon-stock
    replicaCount: 1
    image:
      repository: registry.mulmuri.dev/fetch-system-worker
      tag: latest
      imagePullPolicy: Always
    env:
      polygonSecretKey: ""
      platform: POLYGON
      market: STOCK

  kis-stock:
    name: kis-stock
    replicaCount: 0
    image:
      repository: registry.mulmuri.dev/fetch-system-worker
      tag: latest
      imagePullPolicy: Always
    env:
      kisAppKey: ""
      kisSecretKey: ""
      platform: KIS
      market: STOCK

streams:
  image:
    repository: registry.mulmuri.dev/fetch-system-streams
    tag: latest
    imagePullPolicy: Always
  env:
    kafkaBootstrapHost: fetch-system-kafka:9092
    etcdHost: fetch-system-etcd:2379
    otelEndpoint: fetch-system-opentelemetry-collector:4317
