apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: atlantis-vs
  namespace: atlantis
spec:
  hosts:
  - atlantis.goboolean.io
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - route:
    - destination:
        host: atlantis.atlantis.svc.cluster.local
        port:
          number: 80