apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Chart.Name }}-dbiniter"
spec:
  template:
    metadata:
      name: "{{ .Chart.Name }}-dbiniter"
    spec:
      containers:
      - name: dbiniter
        image: "{{ .Values.dbiniter.image.repository }}:{{ .Values.dbiniter.image.tag }}"
        imagePullPolicy: "{{ .Values.dbiniter.image.imagePullPolicy }}"
        env:
        - name: POSTGRES_HOST
          value: "{{ .Values.dbiniter.env.postgresqlHost }}"
        - name: POSTGRES_PORT
          value: "{{ .Values.dbiniter.env.postgresqlPort }}"
        - name: POSTGRES_USER
          value: "{{ .Values.dbiniter.env.postgresqlUser }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.dbiniter.env.postgresqlPassword }}"
        - name: POSTGRES_DATABASE
          value: "{{ .Values.dbiniter.env.postgresqlDatabase }}"
        - name: POLYGON_SECRET_KEY
          value: "{{ .Values.dbiniter.env.polygonSecretKey }}"
      restartPolicy: Never
  backoffLimit: 3
  