kafka:
  auth:
    enabled: false
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
  broker:
    enabled: true
    replicaCount: 3
  controller:
    enabled: false
    replicaCount: 0
  zookeeper:
    enabled: true
    replicaCount: 1
  kraft:
    enabled: false
  service:
    type: ClusterIP

schema-registry:
  service:
    type: LoadBalancer
  kafka:
    enabled: false
    auth:
      protocol: {}
    service:
      ports:
        client: {}
  externalKafka:
    brokers: PLAINTEXT://kafka.kafka.svc.cluster.local:9092
    listener:
      protocol: PLAINTEXT